### ISSUE TITLE
The ()[]{}!+ characters really trouble me.

### ISSUE THREAD

**Issue by ybingo** [alcuadrado/hieroglyphy#12]
I'm a student,there's a test and one question is all these ()[]{}!+ characters.It's about coding,so I wonder there is any thing can translate ()[]{}!+ into normal javascript code.Thanks!

**Comment by alcuadrado** [comment]
Wow, that test is super harsh! I'm afraid there's not a universal way of doing that. 

You can read [this article](http://patriciopalladino.com/blog/2012/08/09/non-alphanumeric-javascript.html) to learn more about it.
