### ISSUE TITLE
reversing hieroglyphy

### ISSUE THREAD

**Issue by thisisrootbug** [alcuadrado/hieroglyphy#13]
hi is there any way to reverse the output back to normal javascript

**Comment by kernelsmith** [comment]
You have to actually run the code through a JavaScript engine So, the only way to really see it, is to debug a JS engine, like say node.js, and put a breakpoint after the code has been interpreted, but before it is eval'd

**Comment by kernelsmith** [comment]
A more complete answer can be found on issue #10

**Comment by thisisrootbug** [comment]
thank you
