### ISSUE TITLE
The blog post in your description is offline

### ISSUE THREAD

**Issue by jthemphill** [alcuadrado/hieroglyphy#14]
http://patriciopalladino.com/blog/2012/08/09/non-alphanumeric-javascript.html gives a 404. This makes me really sad, as I think it's an article of historical importance in JavaScript programming, general programming language design, and language security.

**Comment by alexandernst** [comment]
This is the latest internet archive: https://web.archive.org/web/20220121095034/http://patriciopalladino.com/blog/2012/08/09/non-alphanumeric-javascript.html

**Comment by kernelsmith** [comment]
I'm guessing @alcuadrado stopped paying for, or hosting, his blog site. I haven't talked with him since before Covid

**Comment by kernelsmith** [comment]
In theory, a version of the blog could be put here in markdown and rendered with github pages if so desired. I don't have rights on this repo, but I could put it up on https://github.com/kernelsmith/hieroglyphy-ruby or at least a facsimile

**Comment by alcuadrado** [comment]
Hey! It's a nice surprise to see activity in this repository.

I decided to replace my site with a minimal one some time ago.

You can find the last (unrendered) version here: https://github.com/alcuadrado/alcuadrado.github.com/blob/0710e5ccae4fae9c5763d86dd9014d9f3edcc71d/_posts/2012-08-10-non-alphanumeric-javascript.md

**Comment by alcuadrado** [comment]
I just replaced the description with the archive.org version.

**Comment by alcuadrado** [comment]
I changed my mind, so I made that link work again, mentioning the archive.org version there.

> I think it's an article of historical importance in JavaScript programming, general programming language design, and language security.

Thanks for raising this issue, and these kind words :)
